# Generated by Django 6.1.1 on 2026-10-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corptenant',
            name='company_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corptenant',
            name='employee_count_estimate',
            field=models.CharField(blank=True, help_text='e.g., 1-50, 51-200', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corptenant',
            name='headquarters_location',
            field=models.CharField(blank=True, help_text='City, State, or Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corptenant',
            name='industry_type',
            field=models.CharField(blank=True, help_text='e.g., Healthcare, Finance, IT', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='corptenant',
            name='registration_number',
            field=models.CharField(blank=True, help_text='CIN, GSTIN, or Tax ID', max_length=100, null=True),
        ),
    ]
