# Generated by Django 6.1.1 on 2026-10-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_corptenant_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corptenant',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='corptenant',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
