# Generated by Django 6.1.1 on 2026-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_corptenant_email_otp_corptenant_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corptenant',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='corptenant',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='corpuser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='corpuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
